---
# tasks file for deploy
- name: Set fact
  ansible.builtin.set_fact:
    client_path: "{{ composer_path }}/{{ client_name }}-{{ client_id }}"

- name: Ensure base docker images exists
  ansible.builtin.debug:
    msg: "Pulling Docker"

- name: Ensure client's composer path exists
  ansible.builtin.file:
    path: "{{ client_path }}"
    state: directory
    mode: '0755'

- name: Generate docker-compose
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ client_path }}/docker-compose.yml"
    mode: '0644'

- name: Generate var file for client's docker-compose
  ansible.builtin.template:
    src: varfile.env.j2
    dest: "{{ client_path }}/varfile.env"
    mode: '0644'

- name: Running docker-compose
  community.docker.docker_compose:
    project_src: "{{ client_path }}"
