---
- name: Deploy front-marketplace image
  ansible.builtin.import_tasks: marketplace-front-deploy.yml
  tags:
    - marketplace
    - front

- name: Deploy api-marketplace image
  ansible.builtin.import_tasks: marketplace-api-deploy.yml
  tags:
    - marketplace
    - api

- name: Deploy front-crm image
  ansible.builtin.import_tasks: crm-front-deploy.yml
  tags:
    - crm
    - front

- name: Deploy api-crm image
  ansible.builtin.import_tasks: crm-api-deploy.yml
  tags:
    - crm
    - api
