- name: Ensure composer path exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ composer_path }}"
    - "{{ composer_path }}/api"
    - "{{ composer_path }}/front"

- name: Ensure builder paths exists
  ansible.builtin.file:
    path: "{{ builder_path }}"
    state: directory
    mode: '0755'
